// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Address: typeof import('./src/components/views/address/Address.vue')['default']
    AddressEdit: typeof import('./src/components/views/addressEdit/AddressEdit.vue')['default']
    Appraise: typeof import('./src/components/views/store/components/Appraise.vue')['default']
    Cart: typeof import('./src/components/views/cart/Cart.vue')['default']
    CartDetail: typeof import('./src/components/views/cart/components/CartDetail.vue')['default']
    CreateOrder: typeof import('./src/components/views/createOrder/CreateOrder.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    FoodList: typeof import('./src/components/views/store/components/FoodList.vue')['default']
    Footer: typeof import('./src/components/footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Home: typeof import('./src/components/views/home/Home.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    Login: typeof import('./src/components/views/login/Login.vue')['default']
    Mine: typeof import('./src/components/views/mine/Mine.vue')['default']
    NavList: typeof import('./src/components/views/home/components/NavList.vue')['default']
    NavListItem: typeof import('./src/components/views/home/components/NavListItem.vue')['default']
    Order: typeof import('./src/components/views/order/Order.vue')['default']
    Register: typeof import('./src/components/views/login/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Store: typeof import('./src/components/views/store/Store.vue')['default']
    StoreProfile: typeof import('./src/components/views/store/components/StoreProfile.vue')['default']
    UserInfoEdit: typeof import('./src/components/views/userInfoEdit/UserInfoEdit.vue')['default']
    VanActionBar: typeof import('vant/es')['ActionBar']
    VanActionBarButton: typeof import('vant/es')['ActionBarButton']
    VanActionBarIcon: typeof import('vant/es')['ActionBarIcon']
    VanAddressEdit: typeof import('vant/es')['AddressEdit']
    VanAddressList: typeof import('vant/es')['AddressList']
    VanCard: typeof import('vant/es')['Card']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCheckboxGroup: typeof import('vant/es')['CheckboxGroup']
    VanContactCard: typeof import('vant/es')['ContactCard']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanSidebar: typeof import('vant/es')['Sidebar']
    VanSidebarItem: typeof import('vant/es')['SidebarItem']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSubmitBar: typeof import('vant/es')['SubmitBar']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
